sudo: required
language: java
jdk: oraclejdk11

services:
  - docker

install: true

git:
  quiet: true

cache:
  directories:
  - $HOME/.m2

before_script:
  - cd $HOME
  - git clone -b release/0.2.1 --single-branch https://github.com/hashgraph/hedera-sdk-java.git
  - cd hedera-sdk-java
  - cd $TRAVIS_BUILD_DIR

script:
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean verify; mvn package; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then ./build-and-push.sh; fi

branches:
  only:
  - master
