sudo: false
language: java
jdk: oraclejdk11

install: true

git:
  quiet: true
  
cache:
  directories:
  - $HOME/.m2

before_script:
  - cd $HOME
  - git clone -b release/0.2.1 --single-branch https://github.com/hashgraph/hedera-sdk-java.git
  - cd hedera-sdk-java
  - mvn clean install
  - cd $TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: build
      script:
        - mvn clean install
    - stage: test
      script:
        - mvn verify
    - stage: docker-publish
      script:
        - mvn dockerfile:push
  
branches:
  only:
  - master
