logging.level.org.springframework: INFO
logging.level.com.hedera.sdk.node.HederaNode: WARN

mongo-host: "localhost"
mongo-db: "pl-test"
mongo-user: "admin"
mongo-pass: "admin"


spring:
  data:
    mongodb:
      uri: "mongodb://${mongo-user}:${mongo-pass}@${mongo-host}/${mongo-db}?retryWrites=true"
  profiles:
#    include: 'dev'

payper:
  baseUrl: 'http://localhost:8080'
  redirectPath: 'pypr/payment-required'
  paymentOptions:
    - id: HEDERA_HBAR_INVOICE
      name: "Hedera Hashgraph"
      currency: HBAR
      currencyName: "HBar"
    - id: LIGHTNING_BTC
      name: "Bitcoin Lightning Network"
      currency: SATOSHI_BTC
      currencyName: "SATS"
    - id: DUMMY_COIN
      name: "Dummy Network"
      currency: DUMMY_COIN
      currencyName: "Dummy Coin"
