logging.level.org.springframework: INFO

spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:AwLXPuo9HPHiFr8b@cluster0-j05v4.mongodb.net/test?retryWrites=true"
      database: pl-test
  profiles:
#    include: 'dev'

payper:
  baseUrl: 'http://localhost:8080'
  redirectPath: 'pypr/payment-required'