price-list:
  apis:
    - name: httpbin
      baseUrl: http://httpbin.org
      walletAddress: 1004
      routes:
        - route: /api/people
          price: 140
        - route: /api/planets
          price: 110