price-list:
  apis:
    - name: httpbin
      baseUrl: http://httpbin.org
      walletAddress: 1019
      routes:
        - route: /api/people
          price: 14
        - route: /api/planets
          price: 13