price-list:
  apis:
    - name: httpbin
      baseUrl: http://httpbin.org
      walletAddress: 1017
      routes:
        - route: /api/people
          price: 340
        - route: /api/planets
          price: 100