logging.level.org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  profiles:
    include: 'price-list'

payper:
  baseUrl: 'http://localhost:8080'
  redirectPath: 'pypr/payment-required'